on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    name: Nofity
    steps:
      - name: Update latest version in realtime database
        uses: w9jds/firebase-trigger@master
        with:
          credentials: ${{ secrets.FIREBASE_CREDENTIALS }}
          databaseUrl: https://learn-simple-code.firebaseio.com
          databaseType: firestore
          path: version/lastRelease
